-- ProblemSet<00>, November <25> <2018> 
-- Submission by <sowmiya.sivalingam.accenture.com> 

1)Select the Employee with the top three salaries
 SELECT NAME FROM EMPLOYEE WHERE SALARY>=(SELECT MAX(SALARY) FROM EMPLOYEE WHERE SALARY<(SELECT MAX(SALARY) FROM EMPLOYEE WHERE SALARY<(SELECT MAX(SALARY) FROM EMPLOYEE))) ORDER BY SALARY;
ADAM WAYNE
PAUL VINCENT
TARA CUMMINGS
Record Count:3

2)Select the Employee with the least salary
 SELECT NAME FROM EMPLOYEE WHERE SALARY=(SELECT MIN(SALARY) FROM EMPLOYEE);
JOHN HELLEN
Record Count:1

3)Select the Employee who does not have a manager in the department table
 SELECT *FROM EMPLOYEE E INNER JOIN DEPT D ON D.DEPT_MANAGER=E.NAME;
A178|BRUCE WILLS|D03|66861|A298|D03|PRODUCT|BRUCE WILLS
A120|TIM ARCHER|D01|48834|A298|D01|HEALTH|TIM ARCHER
A187|ADAM JUSTIN|D02|80543|A298|D02|COMMUNICATIONS|ADAM JUSTIN
A165|NATASHA STEVENS|D05|31377|A298|D05|FINANCE|NATASHA STEVENS
Record Count:4

4)Select the Employee who is also a Manager
SELECT DISTINCT E.NAME FROM EMPLOYEE E INNER JOIN EMPLOYEE M ON E.E_ID=M.MANGER_ID;
TIM ARCHER
ADAM JUSTIN
NATASHA STEVENS
BRUCE WILLS
Record Count:4

5)Select the Empolyee who is a Manager and has least salary
SELECT NAME,MIN(SALARY) FROM(SELECT DISTINCT E.NAME,E.SALARY FROM EMPLOYEE E INNER JOIN EMPLOYEE M ON E.E_ID=M.MANGER_ID)  ;
NATASHA STEVENS|31377
Record count:1

6)Select the total number of Employees in Communications departments
SELECT COUNT(E_ID) FROM(SELECT E_ID FROM EMPLOYEE WHERE DEP_ID=(SELECT DEPT_ID FROM DEPT WHERE DEPT_NAME='COMMUNICATIONS'));
6
Record Count:1

7)Select the Employee in Finance Department who has the top salary
SELECT NAME,MAX(SALARY) FROM EMPLOYEE WHERE DEP_ID=(SELECT DEPT_ID FROM DEPT WHERE DEPT_NAME='FINANCE');
ADAM WAYNE|94324
Record Count:1

8)Select the Employee in product depatment who has the least salary
SELECT NAME,MIN(SALARY) FROM EMPLOYEE WHERE DEP_ID=(SELECT DEPT_ID FROM DEPT WHERE DEPT_NAME='PRODUCT');
NICK MARTIN|50174
Record Count:1

9)Select the count of Empolyees in Health with maximum salary
SELECT COUNT(*) FROM (SELECT MAX(SALARY) FROM(SELECT SALARY FROM EMPLOYEE WHERE DEP_ID=(SELECT DEPT_ID FROM DEPT WHERE DEPT_NAME='HEALTH')));
1
Record Count:1

10)Select the Employees who report to Natasha Stevens
SELECT NAME FROM EMPLOYEE WHERE MANGER_ID=(SELECT E_ID FROM EMPLOYEE WHERE NAME='NATASHA STEVENS');
ADAM WAYNE
JOSEPH ANGELIN
Record Count:2

11)Display the Employee name,Employee count,Dep name,Dept manager in the Health department
SELECT E.NAME,COUNT(*),D.DEPT_NAME,D.DEPT_MANAGER FROM EMPLOYEE E INNER JOIN DEPT D ON D.DEPT_ID=E.DEP_ID WHERE D.DEPT_NAME='HEALTH' GROUP BY E.DEP_ID;
JOHN HELLEN|6|HEALTH|TIM ARCHER
Record Count:1

12)Display the Department id,Employee ids and Manager ids for the Communications department
SELECT E_ID,DEP_ID,MANGER_ID FROM EMPLOYEE WHERE DEP_ID=(SELECT DEPT_ID FROM DEPT WHERE DEPT_NAME='COMMUNICATIONS');
A116|D02|A187
A198|D02|A187
A187|D02|A298
A121|D02|A187
A194|D02|A187
A133|D02|A187
Record:Count:6

13)Select the Average Expenses for Each dept with Dept id and Dept name
SELECT AVG(SALARY),E.DEP_ID,D.DEPT_NAME FROM EMPLOYEE E INNER JOIN DEPT D ON D.DEPT_ID=E.DEP_ID GROUP BY DEP_ID;
54527.6666666667|D01|HEALTH
48271.3333333333|D02|COMMUNICATIONS
58517.5|D03|PRODUCT
64020.0|D04|INSURANCE
56660.3333333333|D05|FINANCE
Record Count:5

14)Select the total expense for the department finance
SELECT SUM(SALARY) FROM EMPLOYEE WHERE DEP_ID=(SELECT DEPT_ID FROM DEPT WHERE DEPT_NAME='FINANCE');
169981
Record Count:1

15)Select the department which spends the least with Dept id and Dept manager name
SELECT MIN(SUM),DEP_ID,DEPT_MANAGER from(SELECT SUM(SALARY) AS SUM,E.DEP_ID,D.DEPT_NAME,D.DEPT_MANAGER FROM EMPLOYEE E INNER JOIN DEPT D ON D.DEPT_ID=E.DEP_ID GROUP BY DEP_ID);
117035|D03|BRUCE WILLS
Record Count:1

16)Select the count of Employees in each department
SELECT COUNT(*),DEP_ID FROM EMPLOYEE GROUP BY DEP_ID;
6|D01
6|D02
2|D03
2|D04
3|D05
Record Count:5

17)Select the count of Employees in each department having salary <10000
SELECT COUNT(*),DEP_ID FROM EMPLOYEE WHERE SALARY<10000 GROUP BY DEP_ID;
Record Count:0

18)Select the total number of Employees in Dept id D04
SELECT COUNT(*),DEP_ID FROM EMPLOYEE WHERE DEP_ID='D04';
2|D04
Record Count:1

19)Select all department details of the Department with Maximum Employees
SELECT MAX(COUNT),DEPT_NAME,DEPT_ID,DEPT_MANAGER FROM(SELECT COUNT(*) AS COUNT,D.DEPT_NAME,D.DEPT_ID,D.DEPT_MANAGER FROM EMPLOYEE E INNER JOIN DEPT D ON D.DEPT_ID=E.DEP_ID GROUP BY DEP_ID);
6|HEALTH|D01|TIM ARCHER
Record Count:1

20)Select the Employees who has Tim Cook as their manager
SELECT NAME FROM EMPLOYEE WHERE MANGER_ID=(SELECT E_ID FROM EMPLOYEE WHERE NAME='TIM COOK');
Record Count:0
